"""GENESIS Automated AGENTS.md Digest Generator.

Renders active architectural decisions, invariants, and environment facts
from SQLite (~/.genesis/memory.db) into a bounded, auto-generated section
of .agents/AGENTS.md during sleep and session-end cycles.
Eliminates cross-session amnesia in closed clients (Antigravity) with zero tool calls.
"""

import logging
import os
from pathlib import Path
import sqlite3

from genesis_memory.core import db as _dbx
import time
from typing import List, Optional, Tuple

logger = logging.getLogger("genesis.digest")

DIGEST_START_MARKER = "<!-- GENESIS_ACTIVE_DIGEST_START -->"
DIGEST_END_MARKER = "<!-- GENESIS_ACTIVE_DIGEST_END -->"
MAX_DIGEST_LINES = 50


def render_digest_content(db_path: Path, max_items: int = 8) -> str:
    """Queries active decisions and facts from SQLite and formats a bounded digest."""
    if not db_path.exists():
        return ""

    conn = _dbx.connect(str(db_path), readonly=True)
    try:
        # Fetch top active decisions and verified facts
        rows = conn.execute(
            "SELECT id, kind, text, utility, accesses, updated FROM episodes "
            "WHERE (status = 'active' OR status IS NULL) AND kind IN ('decision', 'fact') "
            "ORDER BY utility DESC, accesses DESC, updated DESC LIMIT ?",
            (max_items,),
        ).fetchall()
    finally:
        conn.close()

    if not rows:
        return ""

    lines = [
        DIGEST_START_MARKER,
        "<!-- DO NOT EDIT MANUALLY — AUTO-GENERATED BY GENESIS SLEEP CYCLE -->",
        "### 🧠 Active Architectural Digest",
        "",
    ]

    for rid, kind, text, util, acc, upd in rows:
        snippet = text.strip().replace("\n", " ")
        if len(snippet) > 160:
            snippet = snippet[:157] + "..."
        lines.append(f"- **[#{rid} {kind.upper()}]**: {snippet}")

    lines.append("")
    lines.append(DIGEST_END_MARKER)
    return "\n".join(lines)


def update_agents_md(
    agents_md_path: Path,
    db_path: Optional[Path] = None,
    max_items: int = 8,
) -> bool:
    """Updates or inserts the active digest block in the target AGENTS.md file (write-if-changed)."""
    if not agents_md_path.exists():
        logger.warning("Target AGENTS.md not found at %s", agents_md_path)
        return False

    db = db_path or Path.home() / ".genesis" / "memory.db"
    new_digest = render_digest_content(db, max_items=max_items)
    if not new_digest:
        return False

    content = agents_md_path.read_text(encoding="utf-8")

    if DIGEST_START_MARKER in content and DIGEST_END_MARKER in content:
        prefix, rest = content.split(DIGEST_START_MARKER, 1)
        existing_digest, suffix = rest.split(DIGEST_END_MARKER, 1)
        existing_block = (DIGEST_START_MARKER + existing_digest + DIGEST_END_MARKER).strip()
        if existing_block == new_digest.strip():
            # Content is completely identical: avoid unnecessary write to preserve prompt cache
            return False
        updated_content = prefix.rstrip() + "\n\n" + new_digest + "\n\n" + suffix.lstrip()
    else:
        # Append before 'Core Architectural Specifications' or at the bottom
        if "## Core Architectural Specifications" in content:
            parts = content.split("## Core Architectural Specifications", 1)
            updated_content = parts[0].rstrip() + "\n\n" + new_digest + "\n\n## Core Architectural Specifications" + parts[1]
        else:
            updated_content = content.rstrip() + "\n\n" + new_digest + "\n"

    agents_md_path.write_text(updated_content, encoding="utf-8")
    return True


if __name__ == "__main__":
    repo_root = Path(__file__).resolve().parent.parent.parent
    target_agents_md = repo_root / ".agents" / "AGENTS.md"
    success = update_agents_md(target_agents_md)
    print(f"AGENTS.md digest updated: {success}")
