"""Regenerate docs/MCP_SPEC.md from the daemon's TOOLS (single source of truth).

The hand-maintained spec drifted (17 rows, wrong params like content/tags/k).
Run:  C:\\Python314\\python scripts/gen_mcp_spec.py
Check: tests/test_mcp_spec_sync.py fails if the doc is stale.
"""

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from genesis_memory.daemon.server import GATEWAY_TOOL, TOOLS  # noqa: E402


def _fmt_params(schema: dict) -> str:
    props = (schema or {}).get("properties", {}) or {}
    required = set((schema or {}).get("required", []) or [])
    if not props:
        return "none"
    bits = []
    for name, spec in props.items():
        spec = spec if isinstance(spec, dict) else {}
        ptype = spec.get("type", "any")
        if ptype == "array" and isinstance(spec.get("items"), dict):
            ptype = f"list[{spec['items'].get('type', 'any')}]"
        enum = spec.get("enum")
        if enum:
            ptype += f" ({'/'.join(str(e) for e in enum)})"
        star = " *" if name in required else ""
        bits.append(f"`{name}` ({ptype}){star}")
    return ", ".join(bits)


def render() -> str:
    lines = [
        "# GENESIS Memory MCP Tools Specification",
        "",
        "> Auto-generated by `scripts/gen_mcp_spec.py` from",
        "> `genesis_memory.daemon.server.TOOLS` — do not edit by hand.",
        "> `*` marks a required parameter.",
        "",
        "The Model Context Protocol (MCP) server runs via standard I/O (JSON-RPC)",
        "and exposes the following tools",
        f"({len(TOOLS)} cognitive tools + 1 `genesis` gateway tool):",
        "",
        "| Tool Name | Parameters | Description |",
        "|---|---|---|",
    ]
    for tool in TOOLS:
        schema = tool.get("inputSchema", {})
        params = _fmt_params(schema)
        desc = " ".join(tool.get("description", "").split())
        lines.append(f"| `{tool['name']}` | {params} | {desc} |")
    gw_desc = " ".join(GATEWAY_TOOL.get("description", "").split())
    lines.append(f"| `{GATEWAY_TOOL['name']}` | `op` (see gateway ops) * | {gw_desc} |")
    lines += [
        "",
        "Set `GENESIS_MCP_TOOL_MODE=gateway` to advertise only the single",
        "`genesis` tool (all ops route through it with identical arguments).",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    out = REPO / "docs" / "MCP_SPEC.md"
    out.write_text(render(), encoding="utf-8")
    print(f"Wrote {out} ({len(TOOLS)} tools + gateway)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
